#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
generated_dir=$(mktemp -d "${TMPDIR:-/tmp}/any-block-proto.XXXXXX")
trap 'rm -rf -- "$generated_dir"' EXIT HUP INT TERM

model_map=Mformat/v1/proto/models.proto=github.com/anyproto/any-block/format/v1/model
struct_map=Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types

cd "$repo_root"
GOGO_NO_UNDERSCORE=1 GOGO_EXPORT_ONEOF_INTERFACE=1 protoc -I . \
  --gogofaster_out="$struct_map,$model_map:$generated_dir" \
  format/v1/proto/models.proto
generated_root="$generated_dir/github.com/anyproto/any-block/format/v1"
generated_model="$generated_root/model/models.pb.go"
target_model=format/v1/model/models.pb.go
target_enums=format/v1/model/json_enums.go
cp "$generated_model" "$target_model"

enum_count=$(grep -c '^[[:space:]]*proto.RegisterEnum' "$target_model")
type_count=$(grep -c '^[[:space:]]*proto.RegisterType' "$target_model")
init_count=$(grep -c '^func init()' "$target_model")
if [ "$enum_count" -eq 0 ] || [ "$type_count" -eq 0 ] || [ "$init_count" -lt 2 ]; then
  echo "unexpected protobuf registration layout; refusing to post-process generated bindings" >&2
  exit 1
fi

# jsonpb resolves named enum values through gogo's global enum registry. Keep
# registration opt-in so the converter can read legacy .pb.json files without
# reintroducing the duplicate-registration panic for applications that already
# link Heart's v1 bindings.
{
  printf '%s\n\n' '// Code generated by codec/anyblockjson/generate.sh. DO NOT EDIT.'
  printf '%s\n\n' 'package model'
  printf '%s\n' 'import ('
  printf '%s\n\n' '    "sync"'
  printf '%s\n' '    "github.com/gogo/protobuf/proto"'
  printf '%s\n\n' ')'
  printf '%s\n\n' 'var registerJSONEnumsOnce sync.Once'
  printf '%s\n' '// RegisterJSONEnums enables named-enum jsonpb decoding for AnyBlock v1 JSON.'
  printf '%s\n' '// It is opt-in so binary codec users can coexist with another v1 Go binding.'
  printf '%s\n' 'func RegisterJSONEnums() {'
  printf '%s\n' '    registerJSONEnumsOnce.Do(func() {'
  sed -n '/^func init() {$/,/^[[:space:]]*proto.RegisterType/p' "$target_model" \
    | sed -n 's/^[[:space:]]*proto\.RegisterEnum/        registerJSONEnum/p'
  printf '%s\n' '    })'
  printf '%s\n\n' '}'
  printf '%s\n' 'func registerJSONEnum(name string, values map[int32]string, names map[string]int32) {'
  printf '%s\n' '    if proto.EnumValueMap(name) == nil {'
  printf '%s\n' '        proto.RegisterEnum(name, values, names)'
  printf '%s\n' '    }'
  printf '%s\n' '}'
} > "$target_enums"

generated_enum_count=$(grep -Fc '        registerJSONEnum(' "$target_enums")
if [ "$generated_enum_count" -ne "$enum_count" ]; then
  echo "expected $enum_count JSON enum registrations, generated $generated_enum_count" >&2
  exit 1
fi

# A Heart migration can temporarily link two Go bindings for the same v1
# protobuf names. gogo's generated global enum registration panics in that
# situation, although the wire definitions are compatible. The converter
# uses concrete generated types and does not need the global type registry,
# so retain descriptors but remove type/enum registration.
perl -0pi -e 's/func init\(\) \{\n.*?\n\}\n\n(?=func init\(\) \{ proto\.RegisterFile)/\/\/ Global protobuf registration is intentionally disabled. The codec can coexist\n\/\/ with applications that already link another AnyBlock v1 Go binding.\n\n/s' \
  "$target_model"

remaining_registration_count=$(grep -Ec 'proto\.Register(Enum|Type)' "$target_model" || true)
remaining_init_count=$(grep -c '^func init()' "$target_model")
register_file_count=$(grep -c 'proto.RegisterFile' "$target_model")
if [ "$remaining_registration_count" -ne 0 ] \
  || [ "$remaining_init_count" -ne $((init_count - 1)) ] \
  || [ "$register_file_count" -ne 1 ]; then
  echo "protobuf registration post-processing did not produce the expected layout" >&2
  exit 1
fi

gofmt -w format/v1/model
