// Code generated from Anytype's bundled vocabulary. DO NOT EDIT.
// source: anytype-heart/pkg/lib/bundle/systemRelations.json

package vocabulary

import domain "github.com/anyproto/any-block/codec/anyblockjson/domain"

const SystemRelationsChecksum = "f15832dd7ff54506512a0ce53c6a97e0047cfe3837689e5076a8d1ac81d6b377"

// SystemRelations contains relations that have some special biz logic depends on them in some objects
// in case EVERY object depend on the relation please add it to RequiredInternalRelations
var SystemRelations = append(RequiredInternalRelations, []domain.RelationKey{
	RelationKeySnippet,
	RelationKeyLayout,
	RelationKeyLayoutAlign,
	RelationKeyCoverId,
	RelationKeyCoverScale,
	RelationKeyCoverType,
	RelationKeyCoverX,
	RelationKeyCoverY,
	RelationKeyFeaturedRelations,
	RelationKeyLinks,
	RelationKeyAddedDate,
	RelationKeySource,
	RelationKeySourceObject,
	RelationKeySetOf,
	RelationKeyRelationFormat,
	RelationKeyRelationKey,
	RelationKeyRelationReadonlyValue,
	RelationKeyRelationDefaultValue,
	RelationKeyRelationMaxCount,
	RelationKeyRelationOptionColor,
	RelationKeyRelationFormatObjectTypes,
	RelationKeyIsReadonly,
	RelationKeyIsDeleted,
	RelationKeyIsHidden,
	RelationKeySpaceShareableStatus,
	RelationKeyIsAclShared,
	RelationKeyIsHiddenDiscovery,
	RelationKeyDone,
	RelationKeyTemplateIsBundled,
	RelationKeySmartblockTypes,
	RelationKeyTargetObjectType,
	RelationKeyRecommendedLayout,
	RelationKeyFileExt,
	RelationKeyFileMimeType,
	RelationKeySizeInBytes,
	RelationKeyOldAnytypeID,
	RelationKeySpaceDashboardId,
	RelationKeyRecommendedRelations,
	RelationKeyMyParticipantStatus,
	RelationKeyIconOption,
	RelationKeyWidthInPixels,
	RelationKeyHeightInPixels,
	RelationKeyFileExt,
	RelationKeySizeInBytes,
	RelationKeySourceFilePath,
	RelationKeyFileSyncStatus,
	RelationKeyDefaultTemplateId,
	RelationKeyUniqueKey,
	RelationKeyBacklinks,
	RelationKeyProfileOwnerIdentity,
	RelationKeyFileBackupStatus,
	RelationKeyFileId,
	RelationKeyFileIndexingStatus,
	RelationKeyOrigin,
	RelationKeyRevision,
	RelationKeyImageKind,
	RelationKeyImportType,
	RelationKeySpaceAccessType,
	RelationKeySpaceInviteFileCid,
	RelationKeySpaceInviteFileKey,
	RelationKeySpaceInviteType,
	RelationKeySpaceInvitePermissions,
	RelationKeySpaceInviteHeldByOwner,
	RelationKeyReadersLimit,
	RelationKeyWritersLimit,
	RelationKeySharedSpacesLimit,
	RelationKeyParticipantPermissions,
	RelationKeyParticipantStatus,
	RelationKeyLatestAclHeadId,
	RelationKeyIdentity,
	RelationKeyGlobalName,
	RelationKeyLastUsedDate,
	RelationKeyMentions,
	RelationKeyChatId,
	RelationKeyHasChat,
	RelationKeyTimestamp,
	RelationKeyIconName,
	RelationKeyRecommendedFeaturedRelations,
	RelationKeyRecommendedHiddenRelations,
	RelationKeyRecommendedFileRelations,
	RelationKeyLayoutWidth,
	RelationKeyDefaultViewType,
	RelationKeyDefaultTypeId,
	RelationKeyResolvedLayout,
	RelationKeyPluralName,
	RelationKeyLastMessageDate,
	RelationKeyNotificationSubscribers,
	RelationKeyTemplatePlaceholders,
	RelationKeyCreatedInContext,
}...)
