// Code generated by codec/anyblockjson/generate.sh. DO NOT EDIT.

package model

import (
	"sync"

	"github.com/gogo/protobuf/proto"
)

var registerJSONEnumsOnce sync.Once

// RegisterJSONEnums enables named-enum jsonpb decoding for AnyBlock v1 JSON.
// It is opt-in so binary codec users can coexist with another v1 Go binding.
func RegisterJSONEnums() {
	registerJSONEnumsOnce.Do(func() {
		registerJSONEnum("anytype.model.SmartBlockType", SmartBlockType_name, SmartBlockType_value)
		registerJSONEnum("anytype.model.RelationFormat", RelationFormat_name, RelationFormat_value)
		registerJSONEnum("anytype.model.ObjectOrigin", ObjectOrigin_name, ObjectOrigin_value)
		registerJSONEnum("anytype.model.SpaceStatus", SpaceStatus_name, SpaceStatus_value)
		registerJSONEnum("anytype.model.ParticipantPermissions", ParticipantPermissions_name, ParticipantPermissions_value)
		registerJSONEnum("anytype.model.InviteType", InviteType_name, InviteType_value)
		registerJSONEnum("anytype.model.ParticipantStatus", ParticipantStatus_name, ParticipantStatus_value)
		registerJSONEnum("anytype.model.SpaceAccessType", SpaceAccessType_name, SpaceAccessType_value)
		registerJSONEnum("anytype.model.SpaceUxType", SpaceUxType_name, SpaceUxType_value)
		registerJSONEnum("anytype.model.SpaceType", SpaceType_name, SpaceType_value)
		registerJSONEnum("anytype.model.ImageKind", ImageKind_name, ImageKind_value)
		registerJSONEnum("anytype.model.FileIndexingStatus", FileIndexingStatus_name, FileIndexingStatus_value)
		registerJSONEnum("anytype.model.SpaceShareableStatus", SpaceShareableStatus_name, SpaceShareableStatus_value)
		registerJSONEnum("anytype.model.NameserviceNameType", NameserviceNameType_name, NameserviceNameType_value)
		registerJSONEnum("anytype.model.DeviceNetworkType", DeviceNetworkType_name, DeviceNetworkType_value)
		registerJSONEnum("anytype.model.SyncStatus", SyncStatus_name, SyncStatus_value)
		registerJSONEnum("anytype.model.SyncError", SyncError_name, SyncError_value)
		registerJSONEnum("anytype.model.TemplateNamePrefillType", TemplateNamePrefillType_name, TemplateNamePrefillType_value)
		registerJSONEnum("anytype.model.SearchMessageSortKey", SearchMessageSortKey_name, SearchMessageSortKey_value)
		registerJSONEnum("anytype.model.SearchMessageSortType", SearchMessageSortType_name, SearchMessageSortType_value)
		registerJSONEnum("anytype.model.BlockPosition", BlockPosition_name, BlockPosition_value)
		registerJSONEnum("anytype.model.BlockAlign", BlockAlign_name, BlockAlign_value)
		registerJSONEnum("anytype.model.BlockVerticalAlign", BlockVerticalAlign_name, BlockVerticalAlign_value)
		registerJSONEnum("anytype.model.BlockContentLayoutStyle", BlockContentLayoutStyle_name, BlockContentLayoutStyle_value)
		registerJSONEnum("anytype.model.BlockContentLinkIconSize", BlockContentLinkIconSize_name, BlockContentLinkIconSize_value)
		registerJSONEnum("anytype.model.BlockContentLinkStyle", BlockContentLinkStyle_name, BlockContentLinkStyle_value)
		registerJSONEnum("anytype.model.BlockContentLinkDescription", BlockContentLinkDescription_name, BlockContentLinkDescription_value)
		registerJSONEnum("anytype.model.BlockContentLinkCardStyle", BlockContentLinkCardStyle_name, BlockContentLinkCardStyle_value)
		registerJSONEnum("anytype.model.BlockContentDivStyle", BlockContentDivStyle_name, BlockContentDivStyle_value)
		registerJSONEnum("anytype.model.BlockContentBookmarkState", BlockContentBookmarkState_name, BlockContentBookmarkState_value)
		registerJSONEnum("anytype.model.BlockContentTextStyle", BlockContentTextStyle_name, BlockContentTextStyle_value)
		registerJSONEnum("anytype.model.BlockContentTextMarkType", BlockContentTextMarkType_name, BlockContentTextMarkType_value)
		registerJSONEnum("anytype.model.BlockContentFileType", BlockContentFileType_name, BlockContentFileType_value)
		registerJSONEnum("anytype.model.BlockContentFileStyle", BlockContentFileStyle_name, BlockContentFileStyle_value)
		registerJSONEnum("anytype.model.BlockContentFileState", BlockContentFileState_name, BlockContentFileState_value)
		registerJSONEnum("anytype.model.BlockContentDataviewViewType", BlockContentDataviewViewType_name, BlockContentDataviewViewType_value)
		registerJSONEnum("anytype.model.BlockContentDataviewViewSize", BlockContentDataviewViewSize_name, BlockContentDataviewViewSize_value)
		registerJSONEnum("anytype.model.BlockContentDataviewViewListSize", BlockContentDataviewViewListSize_name, BlockContentDataviewViewListSize_value)
		registerJSONEnum("anytype.model.BlockContentDataviewRelationDateFormat", BlockContentDataviewRelationDateFormat_name, BlockContentDataviewRelationDateFormat_value)
		registerJSONEnum("anytype.model.BlockContentDataviewRelationTimeFormat", BlockContentDataviewRelationTimeFormat_name, BlockContentDataviewRelationTimeFormat_value)
		registerJSONEnum("anytype.model.BlockContentDataviewRelationFormulaType", BlockContentDataviewRelationFormulaType_name, BlockContentDataviewRelationFormulaType_value)
		registerJSONEnum("anytype.model.BlockContentDataviewSortType", BlockContentDataviewSortType_name, BlockContentDataviewSortType_value)
		registerJSONEnum("anytype.model.BlockContentDataviewSortEmptyType", BlockContentDataviewSortEmptyType_name, BlockContentDataviewSortEmptyType_value)
		registerJSONEnum("anytype.model.BlockContentDataviewFilterOperator", BlockContentDataviewFilterOperator_name, BlockContentDataviewFilterOperator_value)
		registerJSONEnum("anytype.model.BlockContentDataviewFilterCondition", BlockContentDataviewFilterCondition_name, BlockContentDataviewFilterCondition_value)
		registerJSONEnum("anytype.model.BlockContentDataviewFilterQuickOption", BlockContentDataviewFilterQuickOption_name, BlockContentDataviewFilterQuickOption_value)
		registerJSONEnum("anytype.model.BlockContentLatexProcessor", BlockContentLatexProcessor_name, BlockContentLatexProcessor_value)
		registerJSONEnum("anytype.model.BlockContentWidgetLayout", BlockContentWidgetLayout_name, BlockContentWidgetLayout_value)
		registerJSONEnum("anytype.model.AccountStatusType", AccountStatusType_name, AccountStatusType_value)
		registerJSONEnum("anytype.model.AccountAuthLocalApiScope", AccountAuthLocalApiScope_name, AccountAuthLocalApiScope_value)
		registerJSONEnum("anytype.model.LinkPreviewType", LinkPreviewType_name, LinkPreviewType_value)
		registerJSONEnum("anytype.model.RestrictionsObjectRestriction", RestrictionsObjectRestriction_name, RestrictionsObjectRestriction_value)
		registerJSONEnum("anytype.model.RestrictionsDataviewRestriction", RestrictionsDataviewRestriction_name, RestrictionsDataviewRestriction_value)
		registerJSONEnum("anytype.model.ObjectTypeLayout", ObjectTypeLayout_name, ObjectTypeLayout_value)
		registerJSONEnum("anytype.model.RelationScope", RelationScope_name, RelationScope_value)
		registerJSONEnum("anytype.model.RelationDataSource", RelationDataSource_name, RelationDataSource_value)
		registerJSONEnum("anytype.model.InternalFlagValue", InternalFlagValue_name, InternalFlagValue_value)
		registerJSONEnum("anytype.model.NotificationStatus", NotificationStatus_name, NotificationStatus_value)
		registerJSONEnum("anytype.model.NotificationActionType", NotificationActionType_name, NotificationActionType_value)
		registerJSONEnum("anytype.model.NotificationExportCode", NotificationExportCode_name, NotificationExportCode_value)
		registerJSONEnum("anytype.model.ExportFormat", ExportFormat_name, ExportFormat_value)
		registerJSONEnum("anytype.model.ImportType", ImportType_name, ImportType_value)
		registerJSONEnum("anytype.model.ImportErrorCode", ImportErrorCode_name, ImportErrorCode_value)
		registerJSONEnum("anytype.model.MembershipStatus", MembershipStatus_name, MembershipStatus_value)
		registerJSONEnum("anytype.model.MembershipPaymentMethod", MembershipPaymentMethod_name, MembershipPaymentMethod_value)
		registerJSONEnum("anytype.model.MembershipEmailVerificationStatus", MembershipEmailVerificationStatus_name, MembershipEmailVerificationStatus_value)
		registerJSONEnum("anytype.model.MembershipTierDataPeriodType", MembershipTierDataPeriodType_name, MembershipTierDataPeriodType_value)
		registerJSONEnum("anytype.model.MembershipV2Platform", MembershipV2Platform_name, MembershipV2Platform_value)
		registerJSONEnum("anytype.model.MembershipV2PaymentProvider", MembershipV2PaymentProvider_name, MembershipV2PaymentProvider_value)
		registerJSONEnum("anytype.model.MembershipV2Period", MembershipV2Period_name, MembershipV2Period_value)
		registerJSONEnum("anytype.model.MembershipV2ProductStatusStatus", MembershipV2ProductStatusStatus_name, MembershipV2ProductStatusStatus_value)
		registerJSONEnum("anytype.model.ChatMessageAttachmentAttachmentType", ChatMessageAttachmentAttachmentType_name, ChatMessageAttachmentAttachmentType_value)
		registerJSONEnum("anytype.model.ChatMessageMessageBlockLinkLinkType", ChatMessageMessageBlockLinkLinkType_name, ChatMessageMessageBlockLinkLinkType_value)
		registerJSONEnum("anytype.model.PlaceholderType", PlaceholderType_name, PlaceholderType_value)
	})
}

func registerJSONEnum(name string, values map[int32]string, names map[string]int32) {
	if proto.EnumValueMap(name) == nil {
		proto.RegisterEnum(name, values, names)
	}
}
